# Copyright (c) 2026 GDG on Campus Farmingdale State College
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

body:
  - attributes:
      description: If any of these required steps are not taken, we may not be able to review your issue. Help us to help you!
      label: Bug Report Checklist
      options:
        - label: I have pulled the latest `master` branch of the repository.
          required: true
        - label: I have [searched for related issues](https://github.com/GDSC-FSC/gdg-fsc-website/issues?q=is%3Aissue) and found none that matched my issue.
          required: true
    type: checkboxes
  - attributes:
      description: What would you like to report?
      label: Overview
    type: textarea
    validations:
      required: true
  - attributes:
      description: Any additional info you'd like to provide.
      label: Additional Info
    type: textarea
description: Report a typo or missing area of documentation
labels:
  - "area: documentation"
name: 📝 Documentation
title: "📝 Documentation: <short description of the request>"
