description: Prepares the repo for a typical CI job

name: Prepare

runs:
  steps:
    - uses: oven-sh/setup-bun@v2
      with:
        bun-version: latest
    - run: bun install --frozen-lockfile
      shell: bash
  using: composite
